# Generated by Django 5.0 on 2024-06-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Custom_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
